// Skill label → simple-icons slug. Only labels listed here get a mark; everything else stays text.
export const BRAND_SLUGS = {
  React: "react",
  "Next.js": "nextdotjs",
  TypeScript: "typescript",
  JavaScript: "javascript",
  "Node.js": "nodedotjs",
  ".NET Core": "dotnet",
  "ASP.NET Core MVC": "dotnet",
  PostgreSQL: "postgresql",
  "Tailwind CSS": "tailwindcss",
  "shadcn/ui": "shadcnui",
  "React Native": "react",
  Expo: "expo",
  Electron: "electron",
  Express: "express",
  Redis: "redis",
  RabbitMQ: "rabbitmq",
  MySQL: "mysql",
  MongoDB: "mongodb",
  SQLite: "sqlite",
  Convex: "convex",
  Docker: "docker",
  NGINX: "nginx",
  Linux: "linux",
  Stripe: "stripe",
  "OAuth and JWT": "jsonwebtokens",
  Cypress: "cypress",
  Selenium: "selenium",
  Vitest: "vitest",
  Figma: "figma",
  "C++ (libobs, ClipVault)": "cplusplus",
  "C++": "cplusplus",
  "FFmpeg and NVENC": "ffmpeg",
  FFmpeg: "ffmpeg",
  "vLLM and LiteLLM serving": "vllm",
  Python: "python",
  Terraform: "terraform",
  "pnpm and Turborepo": "pnpm",
  "Git and GitHub": "github",
  "GitHub Actions": "githubactions",
  Zod: "zod",
  "OpenAPI and Swagger": "openapiinitiative",
  Postman: "postman",
  Linear: "linear",
  Jira: "jira",
  Notion: "notion",
  "Claude Code": "claude",
  Cursor: "cursor",
  "GitHub Copilot": "githubcopilot",
  NativeWind: "tailwindcss",
  libobs: "obsstudio",
};
